### ISSUE TITLE
Entry at "charging_finished_at"

### ISSUE THREAD

**Issue by ThomasS1962** [fungus75/ioBroker.zoe2#33]
At Objects "charging_finished_at" it is shown as Invalid Date, in Vis the same tag is shown in Zulu time, i,e, 2021-09-16T17:25:30.000Z.
Could it be converted to local time?

**Comment by fungus75** [comment]
Just for beeing sure: have you tried if the date-field batteryTS is in a correct format?
It is clear, that the value is something completely different to charging_finished_at, but the format is right, isn't it?

If so, all I have to do, is to format the charging_finished_at the same way, isnt' it?

**Comment by ThomasS1962** [comment]
Hi, thanks for the quick reply.
batteryTS is shown in correct date/time format. (String)
charging_finished_at is shown as invalid. (String)
So the format must be the same as batteryTS.

![1](https://user-images.githubusercontent.com/59540901/133674379-b36c5f3d-03a8-401a-82b2-86d06cbf366a.jpg)
.

**Comment by fungus75** [comment]
Ok, I see the problem: you are currently not charging, in that case, the date charging_finished_at was set to "null" which means nothing. The new iobroker-version does something "stupid" with that. Because of not charging, charging would not be finished somehow.

I have adjustet it with a quick fix and set it to 9999-12-31, which means in many systems "never". Please update the adapter and tell me if it helps (I haven't done a new version, but just update it from github)

**Comment by ThomasS1962** [comment]
Ok, thank you for the quick reaction. I will check it tomorrow. 😀

DerPilz ***@***.***> schrieb am Do., 16. Sept. 2021, 21:56:

**Comment by ThomasS1962** [comment]
Hi fungus75,
I updated the adapter and now it works perfect. I see the date 9999-12-31 while not charging and the correct remaining time while the car is charging.
Many thanks for doing that great job!
Have a nice weekend.
